# docker-compose.yml
version: '3.8'

services:
  dinari-node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dinari-testnet-node
    restart: unless-stopped
    ports:
      - "8545:8545"  # RPC port
      - "9000:9000"  # P2P port
    volumes:
      - dinari-data:/app/data
      - ./config:/app/config:ro
    environment:
      - DINARI_NETWORK=testnet
      - GOGC=50
      - GOMEMLIMIT=768MiB
      # IMPORTANT: Set your D-prefix miner address here
      - MINER_ADDRESS=${MINER_ADDRESS:-DB2bn6uXpiFFxmmfVa1fPkAcgEUHMAG9yB}
    # Override CMD to ensure environment variable is passed correctly
    command: >
      sh -c './dinari-node 
      --datadir=/app/data 
      --rpc=0.0.0.0:8545 
      --p2p=/ip4/0.0.0.0/tcp/9000 
      --loglevel=info 
      --miner=$${MINER_ADDRESS} 
      --mine'
    mem_limit: 900m
    mem_reservation: 512m
    cpus: 1.0
    networks:
      - dinari-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  dinari-data:
    driver: local

networks:
  dinari-network:
    driver: bridge