# ==============================================================================
# DinariBlockchain - Kubernetes ConfigMaps
# Application configuration for mainnet and testnet
# ==============================================================================

# ------------------------------------------------------------------------------
# MAINNET CONFIGURATION
# ------------------------------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: dinari-mainnet-config
  namespace: dinari-mainnet
  labels:
    app: dinari-blockchain
    network: mainnet
data:
  # Main configuration file
  config.yaml: |
    # Network configuration
    network:
      mode: "mainnet"
      chain_id: 1
    
    # Node configuration
    node:
      data_dir: "/data"
      log:
        level: "info"
        format: "json"
        output: "stdout"
    
    # JSON-RPC API configuration
    rpc:
      addr: "0.0.0.0:8545"
      
      # TLS configuration (required for mainnet)
      tls:
        enabled: true
        cert_file: "/tls/tls.crt"
        key_file: "/tls/tls.key"
        min_version: "1.3"  # TLS 1.3 only
      
      # Authentication (required for mainnet)
      auth:
        enabled: true
        # API keys loaded from Secret
      
      # CORS configuration
      cors:
        enabled: true
        allowed_origins:
          - "https://api.dinariblockchain.network"
          - "https://explorer.dinariblockchain.network"
      
      # Rate limiting (production settings)
      rate_limit:
        enabled: true
        requests_per_minute: 1000
        burst_size: 200
      
      # Request limits
      max_request_size_mb: 10
      request_timeout_seconds: 60
      read_timeout_seconds: 30
      write_timeout_seconds: 30
    
    # P2P Network configuration
    p2p:
      listen_addr: "/ip4/0.0.0.0/tcp/9000"
      
      # Connection limits (mainnet)
      max_peers: 100
      max_inbound_peers: 60
      max_outbound_peers: 40
      min_peers: 20
      target_peers: 50
      
      # DHT configuration
      dht:
        enabled: true
        mode: "server"
      
      # PubSub configuration
      pubsub:
        enabled: true
        flood_publish: false
      
      # Peer reputation
      reputation:
        ban_threshold: -50
        ban_duration_hours: 24
    
    # Consensus configuration
    consensus:
      pow:
        target_block_time: 15
        difficulty_adjustment_interval: 120
        min_difficulty: 10000
        max_difficulty: 4294967295
        max_future_block_time: 7200
      
      block:
        max_size_mb: 1
        max_transactions: 5000
      
      reward:
        initial_block_reward: 5000000000
        halving_interval: 210000
        max_supply: 2100000000000000
    
    # Mempool configuration
    mempool:
      max_size: 50000
      max_tx_size_kb: 100
      tx_expiry_hours: 48
      max_tx_per_address: 200
      min_fee_per_byte: 10
      rbf_min_increase_percent: 10
    
    # State database configuration
    state:
      cache_size: 50000
      cache_ttl_minutes: 10
      checkpoint_interval: 1000
    
    # Storage configuration (BadgerDB)
    storage:
      badger:
        value_log_file_size_mb: 512
        num_compactors: 4
        num_memtables: 5
        block_cache_size_mb: 256
        index_cache_size_mb: 256
        gc_interval_minutes: 10
        compaction_interval_minutes: 60
    
    # Metrics configuration
    metrics:
      enabled: true
      port: 9090
      update_interval_seconds: 30
    
    # Security configuration
    security:
      max_reorg_depth: 100
      max_orphan_blocks: 100
      orphan_timeout_minutes: 10
      min_diverse_subnets: 10
      max_peers_per_subnet: 15

  # Bootstrap peers for mainnet
  bootstrap-peers.txt: |
    /ip4/seed1.dinariblockchain.network/tcp/9000/p2p/REPLACE_WITH_MAINNET_SEED1_PEER_ID
    /ip4/seed2.dinariblockchain.network/tcp/9000/p2p/REPLACE_WITH_MAINNET_SEED2_PEER_ID
    /ip4/seed3.dinariblockchain.network/tcp/9000/p2p/REPLACE_WITH_MAINNET_SEED3_PEER_ID
    /ip4/seed4.dinariblockchain.network/tcp/9000/p2p/REPLACE_WITH_MAINNET_SEED4_PEER_ID
    /ip4/seed5.dinariblockchain.network/tcp/9000/p2p/REPLACE_WITH_MAINNET_SEED5_PEER_ID

  # Genesis block configuration
  genesis.json: |
    {
      "network": "mainnet",
      "chain_id": 1,
      "timestamp": 1704067200,
      "difficulty": 10000,
      "coinbase": "D00000000000000000000000000000000000000000",
      "message": "Genesis Block - DinariBlockchain for Africa"
    }

---
# ------------------------------------------------------------------------------
# TESTNET CONFIGURATION
# ------------------------------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: dinari-testnet-config
  namespace: dinari-testnet
  labels:
    app: dinari-blockchain
    network: testnet
data:
  # Main configuration file
  config.yaml: |
    # Network configuration
    network:
      mode: "testnet"
      chain_id: 2
    
    # Node configuration
    node:
      data_dir: "/data"
      log:
        level: "debug"
        format: "json"
        output: "stdout"
    
    # JSON-RPC API configuration
    rpc:
      addr: "0.0.0.0:8545"
      
      # TLS configuration (optional for testnet)
      tls:
        enabled: false
      
      # Authentication (optional for testnet)
      auth:
        enabled: false
      
      # CORS configuration (permissive for testnet)
      cors:
        enabled: true
        allowed_origins:
          - "*"
      
      # Rate limiting (relaxed for testnet)
      rate_limit:
        enabled: true
        requests_per_minute: 500
        burst_size: 100
      
      # Request limits
      max_request_size_mb: 10
      request_timeout_seconds: 60
    
    # P2P Network configuration
    p2p:
      listen_addr: "/ip4/0.0.0.0/tcp/9000"
      
      # Connection limits (testnet - smaller)
      max_peers: 50
      max_inbound_peers: 30
      max_outbound_peers: 20
      min_peers: 5
      target_peers: 20
      
      # DHT configuration
      dht:
        enabled: true
        mode: "server"
      
      # PubSub configuration
      pubsub:
        enabled: true
      
      # Peer reputation
      reputation:
        ban_threshold: -50
        ban_duration_hours: 12
    
    # Consensus configuration (easier difficulty for testnet)
    consensus:
      pow:
        target_block_time: 15
        difficulty_adjustment_interval: 120
        min_difficulty: 1000
        max_difficulty: 4294967295
        max_future_block_time: 7200
      
      block:
        max_size_mb: 1
        max_transactions: 5000
      
      reward:
        initial_block_reward: 5000000000
        halving_interval: 210000
        max_supply: 2100000000000000
    
    # Mempool configuration
    mempool:
      max_size: 10000
      max_tx_size_kb: 100
      tx_expiry_hours: 24
      max_tx_per_address: 100
      min_fee_per_byte: 1
      rbf_min_increase_percent: 10
    
    # State database configuration
    state:
      cache_size: 10000
      cache_ttl_minutes: 5
      checkpoint_interval: 1000
    
    # Storage configuration (BadgerDB - smaller for testnet)
    storage:
      badger:
        value_log_file_size_mb: 256
        num_compactors: 2
        num_memtables: 3
        block_cache_size_mb: 100
        index_cache_size_mb: 100
        gc_interval_minutes: 10
        compaction_interval_minutes: 60
    
    # Metrics configuration
    metrics:
      enabled: true
      port: 9090
      update_interval_seconds: 30
    
    # Security configuration
    security:
      max_reorg_depth: 100
      max_orphan_blocks: 100
      orphan_timeout_minutes: 10
      min_diverse_subnets: 5
      max_peers_per_subnet: 10

  # Bootstrap peers for testnet
  bootstrap-peers.txt: |
    /ip4/testnet-seed1.dinariblockchain.network/tcp/9000/p2p/REPLACE_WITH_TESTNET_SEED1_PEER_ID
    /ip4/testnet-seed2.dinariblockchain.network/tcp/9000/p2p/REPLACE_WITH_TESTNET_SEED2_PEER_ID
    /ip4/testnet-seed3.dinariblockchain.network/tcp/9000/p2p/REPLACE_WITH_TESTNET_SEED3_PEER_ID

  # Genesis block configuration
  genesis.json: |
    {
      "network": "testnet",
      "chain_id": 2,
      "timestamp": 1704067200,
      "difficulty": 1000,
      "coinbase": "D00000000000000000000000000000000000000000",
      "message": "Testnet Genesis - DinariBlockchain for Africa"
    }