# AWS EBS CSI storage
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dinari-mainnet-fast-ssd
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  iops: "10000"
  throughput: "500"
  encrypted: "true"