apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 00-namespace.yaml
- 01-configmap.yaml
- 02-secrets.yaml
- 03-storage.yaml
- 04-statefulset.yaml
- 05-services.yaml
- 06-ingress.yaml
- 07-monitoring.yaml

namespace: dinari-mainnet

commonLabels:
  app: dinari-blockchain
  managed-by: kustomize